/** Declaration file generated by dts-gen */

export = winston_koa_logger;

declare function winston_koa_logger(winstonInstance: any): any;

declare namespace winston_koa_logger {
    const prototype: {
    };

}

